# ----- Etapa 1: build con URL del backend de PRODUCCION -----
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# AQUI VA LA URL DEL BACKEND DE PRODUCCION
ARG VITE_API_URL
ARG VITE_RECAPTCHA_SITE_KEY=6Lf3sBUtAAAAAC3vI4IvbYsDqxlpYy2DxHOyTJ_I
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_RECAPTCHA_SITE_KEY=$VITE_RECAPTCHA_SITE_KEY
RUN npm run build

# ----- Etapa 2: servir con nginx -----
FROM nginx:1.27-alpine AS runner
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
