# ============================================

# Configuracion de Mosquitto para AgroSmart

# ============================================

# --- Persistencia ---

persistence true
persistence_location /var/lib/mosquitto/

# --- Logs en pantalla ---

log_dest stdout
log_type all
connection_messages true

# ============================================

# Listener TLS en el puerto 8883 (el que pide el ERS)

# ============================================

listener 8883

# Exigir autenticacion (rechaza conexiones anonimas) -> RF-05

allow_anonymous false
password_file /home/joel117/agrosmart/mqtt/config/passwd

# Certificados TLS -> RF-04

cafile   /home/joel117/agrosmart/mqtt/certs/ca.crt
certfile /home/joel117/agrosmart/mqtt/certs/server.crt
keyfile  /home/joel117/agrosmart/mqtt/certs/server.key

# Forzar TLS 1.2 como minimo

tls_version tlsv1.2

# No exigimos certificado del cliente; autenticamos con usuario/contrasena

require_certificate false
